### ISSUE TITLE
Any plans to support VS2017?

### ISSUE THREAD

**Issue by itsho** [alexcpendleton/Pendletron.Vsix.LocateInTFS#15]
Hi.

Do you have any plans to support VS2017?

seems that in order to support vs2017 you'll need to change the vsixmanifest to V2.

example:
https://github.com/fsprojects/Paket.VisualStudio/pull/133/commits/20eef3a1d3d4dba08ac77fdb2fc9516e6cfbf69e

Note: using V2 means that it won't support VS2010. 😞 

Thanks.

**Comment by alexcpendleton** [comment]
Yes, I do plan to update it. Not being able to support VS2010 is one of the reasons I haven't done it yet. I will probably end up with a version for 2010-2015, and a separate package for 2017+. Not ideal, but that's what's coming. There's a PR you can track (#14) if you want.

**Comment by itsho** [comment]
Thanks!

**Comment by alexcpendleton** [comment]
This extension is now available for VS 2017, except it had to be a separate product due to the extension framework changes. You can find it the new version here: [https://marketplace.visualstudio.com/items?itemName=AlexPendleton.LocateinTFS2017](https://marketplace.visualstudio.com/items?itemName=AlexPendleton.LocateinTFS2017)
